#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/vscode/bin/linux-x64/848b80aeb52026648a8ff9f7c45a9b0a80641e2e/node" "/home/vscode/.vscode-remote/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"